import "./globals.css";
import { Poppins, Commissioner } from "next/font/google";

const poppins = Poppins({
  weight: ["500", "600", "700"],
  display: "swap",
  subsets: ["latin"],
  variable: "--font-poppins"
});

const comissioner = Commissioner({
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  subsets: ["latin"],
  variable: "--font-comissioner"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={comissioner.className}>{children}</body>
    </html>
  );
}
