# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - '3001:3000'
#     depends_on:
#       - db
#     environment:
#       MONGO_URI: mongodb://db:27017/mydatabase

#   db:
#     image: mongo
#     ports:
#       - '27017:27017'

version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - ./data:/data/dbnpm
