// import Profile from './Profile/index';
export { default as Hero } from "./Hero";
export { default as SearchBar } from "./SearchBar";
export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as CardRecipe } from "./CardRecipe";
export { default as HomeCards } from "./HomeCards";
export { default as HomeInfo } from "./HomeInfo";
export { default as Contact } from "./Contact";
export { default as ContactForm } from "./ContactForm";
export { default as Testimonials } from "./Testimonials";
export { default as Profile } from "./Profile";
